"""Sources officielles — préparation au test / examen civique français."""

from src.scraping.spec import SourceSpec

FORMATION = "https://formation-civique.interieur.gouv.fr"

CIVIC_TEST_SOURCES: list[SourceSpec] = [
    # --- Portail formation civique (ministère de l'Intérieur) ---
    SourceSpec(
        id="fc_portail",
        title="formation-civique.interieur.gouv.fr — accueil",
        url=f"{FORMATION}/",
        category="test_civique",
        kind="html",
        filename="test_civique/formation_civique_accueil.txt",
        publisher="Ministère de l'Intérieur",
    ),
    SourceSpec(
        id="fc_fiches_thematiques",
        title="Fiches par thématiques — index",
        url=f"{FORMATION}/fiches-par-thematiques/",
        category="test_civique",
        kind="html",
        filename="test_civique/fiches_par_thematiques_index.txt",
        publisher="formation-civique.interieur.gouv.fr",
    ),
    SourceSpec(
        id="fc_fiches_journee",
        title="Fiches par journée — index",
        url=f"{FORMATION}/fiches-par-journée/",
        category="test_civique",
        kind="html",
        filename="test_civique/fiches_par_journee_index.txt",
        publisher="formation-civique.interieur.gouv.fr",
    ),
    # --- 5 thèmes officiels (pages hub) ---
    SourceSpec(
        id="fc_theme_principes",
        title="Thème — Principes et valeurs de la République",
        url=f"{FORMATION}/fiches-par-thematiques/principes-et-valeurs-de-la-republique/",
        category="test_civique",
        kind="html",
        filename="test_civique/theme_principes_valeurs.txt",
        publisher="formation-civique.interieur.gouv.fr",
    ),
    SourceSpec(
        id="fc_theme_institutions",
        title="Thème — Système institutionnel et politique",
        url=f"{FORMATION}/fiches-par-thematiques/systeme-institutionnel-et-politique/",
        category="test_civique",
        kind="html",
        filename="test_civique/theme_institutions.txt",
        publisher="formation-civique.interieur.gouv.fr",
    ),
    SourceSpec(
        id="fc_theme_droits",
        title="Thème — Droits et devoirs",
        url=f"{FORMATION}/fiches-par-thematiques/droits-et-devoirs/",
        category="test_civique",
        kind="html",
        filename="test_civique/theme_droits_devoirs.txt",
        publisher="formation-civique.interieur.gouv.fr",
    ),
    SourceSpec(
        id="fc_theme_histoire",
        title="Thème — Histoire, géographie et culture",
        url=f"{FORMATION}/fiches-par-thematiques/histoire-geographie-et-culture/",
        category="test_civique",
        kind="html",
        filename="test_civique/theme_histoire_geo_culture.txt",
        publisher="formation-civique.interieur.gouv.fr",
    ),
    SourceSpec(
        id="fc_theme_vivre",
        title="Thème — Vivre dans la société française",
        url=f"{FORMATION}/fiches-par-thematiques/vivre-dans-la-societe-française/",
        category="test_civique",
        kind="html",
        filename="test_civique/theme_vivre_societe.txt",
        publisher="formation-civique.interieur.gouv.fr",
    ),
    # --- Examen civique : infos, programme, listes officielles ---
    SourceSpec(
        id="fc_examen_infos",
        title="Informations générales sur l'examen civique",
        url=f"{FORMATION}/examen-civique/informations-générales-sur-lexamen-civique/",
        category="test_civique",
        kind="html",
        filename="test_civique/examen_infos_generales.txt",
        publisher="formation-civique.interieur.gouv.fr",
    ),
    SourceSpec(
        id="fc_examen_index",
        title="Examen civique — portail",
        url=f"{FORMATION}/examen-civique/",
        category="test_civique",
        kind="html",
        filename="test_civique/examen_civique_index.txt",
        publisher="formation-civique.interieur.gouv.fr",
    ),
    SourceSpec(
        id="fc_questions_csp",
        title="Liste officielle des questions de connaissance — CSP",
        url=f"{FORMATION}/examen-civique/liste-officielle-des-questions-de-connaissance-csp/",
        category="test_civique",
        kind="html",
        filename="test_civique/liste_questions_csp.txt",
        publisher="formation-civique.interieur.gouv.fr",
    ),
    SourceSpec(
        id="fc_questions_cr",
        title="Liste officielle des questions de connaissance — CR",
        url=f"{FORMATION}/examen-civique/liste-officielle-des-questions-de-connaissance-cr/",
        category="test_civique",
        kind="html",
        filename="test_civique/liste_questions_cr.txt",
        publisher="formation-civique.interieur.gouv.fr",
    ),
    SourceSpec(
        id="immigration_questions_nat_page",
        title="Questions de connaissance — naturalisation (DGEF)",
        url="https://www.immigration.interieur.gouv.fr/Integration-et-Acces-a-la-nationalite/La-nationalite-francaise/Les-procedures-d-acces-a-la-nationalite-francaise",
        category="test_civique",
        kind="html",
        filename="test_civique/immigration_questions_naturalisation.txt",
        publisher="immigration.interieur.gouv.fr",
    ),
    SourceSpec(
        id="datagouv_questions_nat_json",
        title="data.gouv.fr — Questions naturalisation (JSON officiel)",
        url="https://static.data.gouv.fr/resources/examen-civique-naturalisation-questions-de-connaissances-officielles-et-propositions-de-reponses/20260324-161058/data-gouv-qcm-civique-naturalisation.json",
        category="test_civique",
        kind="json",
        filename="test_civique/questions_naturalisation_officielles.json",
        publisher="data.gouv.fr / Ministère de l'Intérieur",
    ),
    # --- Journées de formation (4 jours) ---
    SourceSpec(
        id="fc_journee_1",
        title="Formation civique — Journée 1",
        url=f"{FORMATION}/fiches-par-journée/journée-1/",
        category="test_civique",
        kind="html",
        filename="test_civique/journee_1_index.txt",
        publisher="formation-civique.interieur.gouv.fr",
    ),
    SourceSpec(
        id="fc_journee_2",
        title="Formation civique — Journée 2",
        url=f"{FORMATION}/fiches-par-journée/journée-2/",
        category="test_civique",
        kind="html",
        filename="test_civique/journee_2_index.txt",
        publisher="formation-civique.interieur.gouv.fr",
    ),
    SourceSpec(
        id="fc_journee_3",
        title="Formation civique — Journée 3",
        url=f"{FORMATION}/fiches-par-journée/journée-3/",
        category="test_civique",
        kind="html",
        filename="test_civique/journee_3_index.txt",
        publisher="formation-civique.interieur.gouv.fr",
    ),
    SourceSpec(
        id="fc_journee_4",
        title="Formation civique — Journée 4",
        url=f"{FORMATION}/fiches-par-journée/journée--4/",
        category="test_civique",
        kind="html",
        filename="test_civique/journee_4_index.txt",
        publisher="formation-civique.interieur.gouv.fr",
    ),
    # --- PDF officiels (immigration / intérieur) ---
    SourceSpec(
        id="livret_citoyen_pdf",
        title="Livret du citoyen (PDF officiel)",
        url="https://www.immigration.interieur.gouv.fr/content/download/131060/1042292/file/Livret_du_citoyen_V2fev2022.pdf",
        category="test_civique",
        kind="pdf",
        filename="test_civique/livret_du_citoyen.pdf",
        publisher="Ministère de l'Intérieur",
    ),
    SourceSpec(
        id="immigration_livret_page",
        title="Page officielle — Le livret du citoyen",
        url="https://www.immigration.interieur.gouv.fr/Integration-et-Acces-a-la-nationalite/La-nationalite-francaise/Le-livret-du-citoyen",
        category="test_civique",
        kind="html",
        filename="test_civique/page_livret_citoyen.txt",
        publisher="immigration.interieur.gouv.fr",
    ),
    SourceSpec(
        id="immigration_charte_page",
        title="Page officielle — Charte des droits et devoirs du citoyen français",
        url="https://www.immigration.interieur.gouv.fr/Integration-et-Acces-a-la-nationalite/La-nationalite-francaise/La-charte-des-droits-et-devoirs-du-citoyen-francais",
        category="test_civique",
        kind="html",
        filename="test_civique/page_charte_droits_devoirs.txt",
        publisher="immigration.interieur.gouv.fr",
    ),
    SourceSpec(
        id="immigration_examen_csp",
        title="Examen civique — première demande titre de séjour pluriannuel",
        url="https://www.immigration.interieur.gouv.fr/Immigration/Examen-civique-pour-une-premiere-demande-de-titre-de-sejour-pluriannuel",
        category="test_civique",
        kind="html",
        filename="test_civique/immigration_examen_csp.txt",
        publisher="immigration.interieur.gouv.fr",
    ),
    SourceSpec(
        id="immigration_formation_civique",
        title="Formation civique — portail immigration",
        url="https://www.immigration.interieur.gouv.fr/Integration-et-Acces-a-la-nationalite/Formation-civique",
        category="test_civique",
        kind="html",
        filename="test_civique/immigration_formation_civique.txt",
        publisher="immigration.interieur.gouv.fr",
    ),
    SourceSpec(
        id="immigration_cir",
        title="Contrat d'intégration républicaine (CIR)",
        url="https://www.immigration.interieur.gouv.fr/Integration-et-Acces-a-la-nationalite/Le-contrat-d-integration-republicaine-CIR",
        category="test_civique",
        kind="html",
        filename="test_civique/contrat_integration_republicaine.txt",
        publisher="immigration.interieur.gouv.fr",
    ),
    # --- service-public.gouv.fr ---
    SourceSpec(
        id="sp_examen_csp",
        title="Carte de séjour : passer l'examen civique",
        url="https://www.service-public.gouv.fr/particuliers/vosdroits/F39530",
        category="test_civique",
        kind="html",
        filename="test_civique/sp_examen_carte_sejour.txt",
        publisher="service-public.gouv.fr",
    ),
    SourceSpec(
        id="sp_examen_nat",
        title="Naturalisation : passer l'examen civique",
        url="https://www.service-public.gouv.fr/particuliers/vosdroits/F39426",
        category="test_civique",
        kind="html",
        filename="test_civique/sp_examen_naturalisation.txt",
        publisher="service-public.gouv.fr",
    ),
    SourceSpec(
        id="sp_actu_examen_2026",
        title="Actualité — nouvel examen civique (janvier 2026)",
        url="https://www.service-public.gouv.fr/particuliers/actualites/A18713",
        category="test_civique",
        kind="html",
        filename="test_civique/sp_actu_examen_2026.txt",
        publisher="service-public.gouv.fr",
    ),
    SourceSpec(
        id="sp_cir",
        title="Contrat d'intégration républicaine (service-public)",
        url="https://www.service-public.gouv.fr/particuliers/vosdroits/F15898",
        category="test_civique",
        kind="html",
        filename="test_civique/sp_contrat_integration.txt",
        publisher="service-public.gouv.fr",
    ),
    SourceSpec(
        id="sp_laicite",
        title="Laïcité — principes et règles",
        url="https://www.service-public.gouv.fr/particuliers/vosdroits/F32823",
        category="test_civique",
        kind="html",
        filename="test_civique/sp_laicite.txt",
        publisher="service-public.gouv.fr",
    ),
    SourceSpec(
        id="sp_droits_fondamentaux",
        title="Droits fondamentaux en France",
        url="https://www.service-public.gouv.fr/particuliers/vosdroits/F31952",
        category="test_civique",
        kind="html",
        filename="test_civique/sp_droits_fondamentaux.txt",
        publisher="service-public.gouv.fr",
    ),
    # --- Textes réglementaires ---
    SourceSpec(
        id="legifrance_arrete_examen_2025",
        title="Arrêté du 10 octobre 2025 — programme et modalités examen civique",
        url="https://www.legifrance.gouv.fr/eli/arrete/2025/10/10/INTV2527907A/jo/texte",
        category="test_civique",
        kind="html",
        filename="test_civique/arrete_examen_civique_2025.txt",
        publisher="Légifrance / JORF",
    ),
    SourceSpec(
        id="vie_publique_integration",
        title="vie-publique.fr — Immigration et intégration",
        url="https://www.vie-publique.fr/discours/selection-discours/immigration-et-integration",
        category="test_civique",
        kind="html",
        filename="test_civique/vie_publique_integration.txt",
        publisher="vie-publique.fr",
    ),
    SourceSpec(
        id="loi_1905_laicite",
        title="Loi de 1905 — séparation Églises et État (Légifrance)",
        url="https://www.legifrance.gouv.fr/loda/id/LEGITEXT000006070166/",
        category="test_civique",
        kind="html",
        filename="test_civique/loi_1905_laicite.txt",
        publisher="Légifrance",
    ),
]

# URLs de départ pour le crawler récursif (fiches détaillées)
FORMATION_CRAWL_SEEDS: list[str] = [
    f"{FORMATION}/fiches-par-thematiques/",
    f"{FORMATION}/fiches-par-journée/",
    f"{FORMATION}/examen-civique/",
]
