"""Catalogue des sources officielles — Constitution, Élections, Justice & Test civique."""

from src.scraping.civic_test_sources import CIVIC_TEST_SOURCES
from src.scraping.justice_sources import JUSTICE_SOURCES
from src.scraping.spec import SourceSpec

__all__ = ["SourceSpec", "OFFICIAL_SOURCES", "sources_by_category"]


# Sources stables (sites gouvernementaux / institutions)
OFFICIAL_SOURCES: list[SourceSpec] = [
    # --- Constitution ---
    SourceSpec(
        id="constitution_pdf_vie_publique",
        title="Constitution du 4 octobre 1958 (texte intégral, maj 2024)",
        url="https://www.vie-publique.fr/files/2024-04/604240050_INT_Constitution-1958_Maj-2024_Web_Extrait.pdf",
        category="constitution",
        kind="pdf",
        filename="constitution_1958_vie_publique_2024.pdf",
        publisher="vie-publique.fr / DILA",
    ),
    SourceSpec(
        id="constitution_conseil_constitutionnel",
        title="Constitution — texte intégral en vigueur",
        url="https://read-only.conseil-constitutionnel.fr/le-bloc-de-constitutionnalite/texte-integral-de-la-constitution-du-4-octobre-1958-en-vigueur",
        category="constitution",
        kind="html",
        filename="constitution_conseil_constitutionnel.txt",
        publisher="Conseil constitutionnel",
    ),
    SourceSpec(
        id="declaration_1789_cc",
        title="Déclaration des droits de l'homme et du citoyen de 1789",
        url="https://read-only.conseil-constitutionnel.fr/le-bloc-de-constitutionnalite/declaration-des-droits-de-l-homme-et-du-citoyen-de-1789",
        category="constitution",
        kind="html",
        filename="declaration_1789.txt",
        publisher="Conseil constitutionnel",
    ),
    SourceSpec(
        id="preambule_1946",
        title="Préambule de la Constitution du 27 octobre 1946",
        url="https://read-only.conseil-constitutionnel.fr/le-bloc-de-constitutionnalite/preambule-de-la-constitution-du-27-octobre-1946",
        category="constitution",
        kind="html",
        filename="preambule_constitution_1946.txt",
        publisher="Conseil constitutionnel",
    ),
    SourceSpec(
        id="charte_environnement_cc",
        title="Charte de l'environnement de 2004",
        url="https://read-only.conseil-constitutionnel.fr/le-bloc-de-constitutionnalite/charte-de-l-environnement-de-2004",
        category="constitution",
        kind="html",
        filename="charte_environnement_2004.txt",
        publisher="Conseil constitutionnel",
    ),
    # --- Élections ---
    SourceSpec(
        id="guide_bureau_vote_pdf",
        title="Guide du bureau de vote — opérations électorales",
        url="https://www.vie-publique.fr/files/collection_number/portrait/photo/9782111742895_MinInt_Guide-du-bureau-de-vote_accessible_0.pdf",
        category="elections",
        kind="pdf",
        filename="guide_bureau_de_vote.pdf",
        publisher="Ministère de l'Intérieur / vie-publique.fr",
    ),
    SourceSpec(
        id="elections_presidentielles_sp",
        title="Élection du président de la République — mode d'emploi",
        url="https://www.service-public.fr/particuliers/vosdroits/F2149",
        category="elections",
        kind="html",
        filename="election_presidentielle_service_public.txt",
        publisher="service-public.fr",
    ),
    SourceSpec(
        id="elections_legislatives_sp",
        title="Élections législatives — mode d'emploi",
        url="https://www.service-public.fr/particuliers/vosdroits/F1944",
        category="elections",
        kind="html",
        filename="elections_legislatives_service_public.txt",
        publisher="service-public.fr",
    ),
    SourceSpec(
        id="elections_municipales_sp",
        title="Élections municipales — mode d'emploi",
        url="https://www.service-public.fr/particuliers/vosdroits/F1961",
        category="elections",
        kind="html",
        filename="elections_municipales_service_public.txt",
        publisher="service-public.fr",
    ),
    SourceSpec(
        id="elections_europeennes_sp",
        title="Élections européennes — mode d'emploi",
        url="https://www.service-public.fr/particuliers/vosdroits/F35778",
        category="elections",
        kind="html",
        filename="elections_europeennes_service_public.txt",
        publisher="service-public.fr",
    ),
    SourceSpec(
        id="insee_participation_scrutins",
        title="INSEE — Taux de participation aux derniers scrutins",
        url="https://www.insee.fr/fr/statistiques/2134437",
        category="elections",
        kind="html",
        filename="insee_participation_scrutins.txt",
        publisher="INSEE",
    ),
    SourceSpec(
        id="insee_participation_europeennes",
        title="INSEE — Participation aux élections européennes",
        url="https://www.insee.fr/fr/statistiques/2409082",
        category="elections",
        kind="html",
        filename="insee_participation_europeennes.txt",
        publisher="INSEE",
    ),
    SourceSpec(
        id="insee_electeurs_inscrits_2024",
        title="INSEE — Électeurs inscrits (élections européennes 2024)",
        url="https://www.insee.fr/fr/statistiques/8192479",
        category="elections",
        kind="html",
        filename="insee_electeurs_inscrits_2024.txt",
        publisher="INSEE",
    ),
    SourceSpec(
        id="elections_interieur_accueil",
        title="Élections en France — portail ministère de l'Intérieur",
        url="https://www.elections.interieur.gouv.fr/",
        category="elections",
        kind="html",
        filename="elections_interieur_portail.txt",
        publisher="elections.interieur.gouv.fr",
    ),
    SourceSpec(
        id="datagouv_elections_hub",
        title="data.gouv.fr — Portail données élections",
        url="https://www.data.gouv.fr/elections",
        category="elections",
        kind="html",
        filename="datagouv_elections_hub.txt",
        publisher="data.gouv.fr",
    ),
    SourceSpec(
        id="inscription_liste_electorale",
        title="S'inscrire sur les listes électorales",
        url="https://www.service-public.fr/particuliers/vosdroits/F1362",
        category="elections",
        kind="html",
        filename="inscription_liste_electorale.txt",
        publisher="service-public.fr",
    ),
    SourceSpec(
        id="vote_par_procuration",
        title="Vote par procuration",
        url="https://www.service-public.fr/particuliers/vosdroits/F1191",
        category="elections",
        kind="html",
        filename="vote_par_procuration.txt",
        publisher="service-public.fr",
    ),
    SourceSpec(
        id="elections_senatoriales_sp",
        title="Élections sénatoriales — mode d'emploi",
        url="https://www.service-public.fr/particuliers/vosdroits/F1619",
        category="elections",
        kind="html",
        filename="elections_senatoriales_service_public.txt",
        publisher="service-public.fr",
    ),
    SourceSpec(
        id="referendum_sp",
        title="Référendum en France",
        url="https://www.service-public.fr/particuliers/vosdroits/F1614",
        category="elections",
        kind="html",
        filename="referendum_service_public.txt",
        publisher="service-public.fr",
    ),
    SourceSpec(
        id="constitution_assemblee",
        title="Constitution — Assemblée nationale (texte de référence)",
        url="https://www.assemblee-nationale.fr/dyn/17/divers/texte_reference/01_constitution",
        category="constitution",
        kind="html",
        filename="constitution_assemblee_nationale.txt",
        publisher="Assemblée nationale",
    ),
    # --- Actualités récentes (2024–2026) ---
    SourceSpec(
        id="revision_constitution_2024_ivg",
        title="Révision constitutionnelle 2024 — IVG (loi du 8 mars 2024)",
        url="https://www.vie-publique.fr/en-bref/293456-une-revision-de-la-constitution-pour-inscrire-le-droit-a-livg",
        category="constitution",
        kind="html",
        filename="revision_constitution_2024_ivg.txt",
        publisher="vie-publique.fr",
    ),
    SourceSpec(
        id="dissolution_2024",
        title="Dissolution de l'Assemblée nationale (juin 2024)",
        url="https://www.vie-publique.fr/en-bref/294558-dissolution-de-lassemblee-nationale",
        category="constitution",
        kind="html",
        filename="dissolution_assemblee_2024.txt",
        publisher="vie-publique.fr",
    ),
    SourceSpec(
        id="europeennes_2024_resultats_vp",
        title="Élections européennes 2024 — résultats officiels",
        url="https://www.vie-publique.fr/en-bref/294559-elections-europeennes-2024-les-resultats",
        category="elections",
        kind="html",
        filename="europeennes_2024_resultats.txt",
        publisher="vie-publique.fr",
    ),
    SourceSpec(
        id="legislatives_2024_t1_vp",
        title="Législatives 2024 — résultats 1er tour",
        url="https://www.vie-publique.fr/en-bref/294751-legislatives-2024-les-resultats-du-premier-tour",
        category="elections",
        kind="html",
        filename="legislatives_2024_t1_resultats.txt",
        publisher="vie-publique.fr",
    ),
    SourceSpec(
        id="legislatives_2024_t2_vp",
        title="Législatives 2024 — résultats 2nd tour",
        url="https://www.vie-publique.fr/en-bref/294864-legislatives-2024-les-resultats-du-second-tour",
        category="elections",
        kind="html",
        filename="legislatives_2024_t2_resultats.txt",
        publisher="vie-publique.fr",
    ),
    SourceSpec(
        id="insee_abstention_2024",
        title="INSEE — Abstention et participation (Portrait social 2024)",
        url="https://www.insee.fr/fr/statistiques/8612556",
        category="elections",
        kind="html",
        filename="insee_abstention_participation_2024.txt",
        publisher="INSEE",
    ),
    SourceSpec(
        id="conseil_constitutionnel_dissolution_2024",
        title="Conseil constitutionnel — décision dissolution 2024",
        url="https://www.conseil-constitutionnel.fr/decision/2024/2024-1035-QPC.htm",
        category="constitution",
        kind="html",
        filename="cc_decision_dissolution_2024.txt",
        publisher="Conseil constitutionnel",
    ),
    SourceSpec(
        id="elections_departementales_sp",
        title="Élections départementales et régionales — mode d'emploi",
        url="https://www.service-public.fr/particuliers/vosdroits/F2160",
        category="elections",
        kind="html",
        filename="elections_departementales_service_public.txt",
        publisher="service-public.fr",
    ),
] + JUSTICE_SOURCES + CIVIC_TEST_SOURCES


def sources_by_category(category: str | None = None) -> list[SourceSpec]:
    if not category:
        return list(OFFICIAL_SOURCES)
    return [s for s in OFFICIAL_SOURCES if s.category == category]
